/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin Mac-mini-von-Duc-4.local 24.0.0 arm64"
#define LGL_COMPILED "Sun Mar 30 16:50:37 CEST 2025"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
